### PR TITLE
localize

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
https://github.com/sebastianha/sfoa/issues/2 please check that this works. Perhaps you could add de (Deutsch)? What do you think? Thank you

**Comment by ovari** [comment]
@sebastianha could you please advise when this has been merged (or not required) so that our fork can be deleted. Thank you

**Comment by ovari** [comment]
Could you please advise when this is merged so we can delete our fork? Thank you

**Comment by sebastianha** [comment]
Hi,
please see the updated project description. This plugin has no support for the latest version of thunderbird because they changed the plugin API. Therefore, it will not be updated.

**Comment by ovari** [comment]
Updated as requested. Can you please merge this? Thank you

**Comment by sebastianha** [comment]
Hi,
this was a misunderstanding: This plugin in the current form is no longer compatible with Thunderbird. Therefore, I will not update this Plugin anymore. It needs a complete rewrite.

**Comment by ovari** [comment]
None of the suggestions are requires and we should delete the fork?

**Comment by sebastianha** [comment]
If there is some time I will create a new plugin which will work with the new api. Then I would be happy to have you again as translator. I really appreciate your work but it does not make any sense now to maintain this plugin here.

**Pull request closed without merging**
